version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: bioinfo_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bioinfo_db
      MYSQL_USER: bio_user
      MYSQL_PASSWORD: bio_pass
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

